### ISSUE TITLE
Windows unit test failures

### ISSUE THREAD

**Issue by gpa14** [hlamer/qutepart#40]
WinPython 32-bit 3.4.3.7Qt5, run_all.py, Windows 8.1 64-bit
Using python parser not C parser
Revision ac6650df386d2804667792607db4887b59de95d1
```
======================================================================
FAIL: test_RegExpr (test_syntax.test_rules.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Grant\Documents\CodeChat\software\qutepart\tests\test_syntax\te
st_rules.py", line 159, in test_RegExpr
    self.assertEqual(rule.regExp.pattern, "[A-Z][A-Za-z\xc0-\xd6\xd8-\xf6\xf8-\x
ff0-9_']*")
AssertionError: "[A-Z][A-Za-z\\300-\\326\\330-\\366\\370-\\3770-9_']*" != "[A-Z]
[A-Za-z\xc0-Ö\xd8-ö\xf8-ÿ0-9_']*"
- [A-Z][A-Za-z\300-\326\330-\366\370-\3770-9_']*
+ [A-Z][A-Za-z\xc0-Ö\xd8-ö\xf8-ÿ0-9_']*


======================================================================
FAIL: test_keyword (test_syntax.test_rules.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Grant\Documents\CodeChat\software\qutepart\tests\test_syntax\te
st_rules.py", line 109, in test_keyword
    self.assertEqual(tryMatch(rule, 0, "var"), 3)
AssertionError: None != 3

----------------------------------------------------------------------
Ran 594 tests in 77.355s

FAILED (failures=2, skipped=8, expected failures=15)

C:\Users\Grant\Documents\CodeChat\software\qutepart\tests>
```

**Comment by bjones1** [comment]
I'll work on this when I can.

**Comment by bjones1** [comment]
Andrei, I did a bit of looking. Would you provide some feedback, since I'm not familiar with the parser?

- In `test_syntax/test_rule.py` line 109, the test wants to match on `var`. However, per ac6650df386d2804667792607db4887b59de95d1, `var` is now in the `keyword` category; doing a `print(rule)` shows items from the controlFlow category:

```
                Rule keyword(while if for break continue return throw try else 
debugger switch with catch case finally do, 0)
                        styleName: controlflow
                        context: None
```

Do you want to change these test to use `if` or some other control flow keyword, or change to using the `keyword` category?

- Changing line 161 of `test_syntax/test_rule.py` to `self.assertEqual(rule.regExp.pattern, "[A-Z][A-Za-z\\300-\\326\\330-\\366\\370-\\3770-9_']*")` makes the test pass. But is this correct -- the RegExp string should be escaped (`\\300`, instead of `\300`)?

**Comment by hlamer** [comment]
Ooops, I forgot to run the tests after the update.
Now all tests are fixed.
There was mistake in the xml file, not in the test.

**Comment by bjones1** [comment]
Great, thanks for the fixes!
